Repository vapor/vapor, pull requests merged in 2018-03, with the labels that each got.

#1529 foundation client
  Sources/Vapor/Engine/FoundationClient.swift
  Sources/Vapor/Services/Config+Default.swift
  Sources/Vapor/Services/Services+Default.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement

#1540 nightly ci builds
  Package.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/RoutingTestsMocks.swift
  circle.yml
Labels: bug, enhancement

#1538 Add Backticks to comments for consistency`s sake
  Sources/Vapor/Content/Content.swift
Labels: enhancement

#1554 fix DateMiddleWare cached timestamp return logic
  Sources/Vapor/Middleware/DateMiddleware.swift
Labels: bug

#1557 Shut down the application's event loop when it gets deallocated.
  Sources/Vapor/Application.swift
Labels: bug, enhancement

#1560 Check to see if path is a directory as well
  Sources/Vapor/Middleware/FileMiddleware.swift
  circle.yml
Labels: bug

#1568 body and data coders
  Sources/Boilerplate/boot.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Commands/CommandConfig.swift
  Sources/Vapor/Content/Content.swift
  Sources/Vapor/Content/ContentCoders.swift
  Sources/Vapor/Content/ContentConfig.swift
  Sources/Vapor/Content/ContentContainer.swift
  Sources/Vapor/Content/DataCoders.swift
  Sources/Vapor/Content/Message+Content.swift
  Sources/Vapor/Content/MultipartContent.swift
  Sources/Vapor/Content/PlaintextEncoder.swift
  Sources/Vapor/Content/QueryContainer.swift
  Sources/Vapor/Content/SingleValueGet.swift
  Sources/Vapor/Deprecated.swift
  Sources/Vapor/Error/Abort.swift
  Sources/Vapor/Error/AbortError.swift
  Sources/Vapor/HTTP/Client.swift
  Sources/Vapor/HTTP/HTTPStatus.swift
  Sources/Vapor/HTTP/QueryContainer.swift
  Sources/Vapor/HTTP/Request.swift
  Sources/Vapor/HTTP/Response.swift
  Sources/Vapor/Routing/LazyMiddlewareRouteGroup.swift
  Sources/Vapor/Utilities/Exports.swift
  Tests/VaporTests/ApplicationTests.swift
  circle.yml
Labels: enhancement

#1570 use environment for command line arguments
  Sources/Boilerplate/configure.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Commands/CommandConfig.swift
  Sources/Vapor/Commands/MainCommand.swift
  Sources/Vapor/Commands/RoutesCommand.swift
  Sources/Vapor/Commands/ServeCommand.swift
  Sources/Vapor/HTTP/EngineServer.swift
  Sources/Vapor/HTTP/Server.swift
  Sources/Vapor/Services/Services+Default.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement
