Repository vapor/vapor, pull requests merged in 2019-12, with the labels that each got.

#2111 req.auth cleanup
  .github/workflows/test.yml
  Sources/Vapor/Authentication/AuthenticationCache.swift
  Sources/Vapor/Authentication/Authenticator.swift
  Sources/Vapor/Authentication/GuardMiddleware.swift
  Sources/Vapor/Authentication/RedirectMiddleware.swift
  Sources/Vapor/Authentication/SessionAuthenticatable.swift
  Sources/Vapor/HTTP/HTTP.swift
  Sources/XCTVapor/XCTHTTPResponse.swift
  Tests/LinuxMain.swift
  Tests/VaporTests/AuthenticationTests.swift
  Tests/VaporTests/XCTestManifests.swift
Labels: enhancement

#2118 beta.2
  Package.swift
  Sources/Development/routes.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Commands/CommandContext+Application.swift
  Sources/Vapor/Commands/RoutesCommand.swift
  Sources/Vapor/Commands/ServeCommand.swift
  Sources/Vapor/Core/Core.swift
  Sources/Vapor/Core/Running.swift
  Sources/Vapor/HTTP/HTTP.swift
  Sources/Vapor/Server/Server.swift
  Sources/Vapor/Services/Provider.swift
  Sources/Vapor/Sessions/Session.swift
  Sources/Vapor/Sessions/Sessions.swift
  Sources/Vapor/Sessions/SessionsMiddleware.swift
  Sources/Vapor/Utilities/Storage.swift
  Sources/Vapor/View/Views.swift
  Sources/XCTVapor/XCTApplication.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/AuthenticationTests.swift
Labels: enhancement

#2120 http provider cleanup
  Sources/Vapor/Application.swift
  Sources/Vapor/Client/Application+Client.swift
  Sources/Vapor/Client/HTTPClient+Client.swift
  Sources/Vapor/Client/Request+Client.swift
  Sources/Vapor/HTTP/ApplicationResponder.swift
  Sources/Vapor/HTTP/HTTP.swift
  Sources/Vapor/Middleware/Application+Middleware.swift
  Sources/Vapor/Routing/Application+Routes.swift
  Sources/Vapor/Server/Application+Server.swift
  Sources/Vapor/Utilities/Storage.swift
  Sources/XCTVapor/XCTApplication.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement

#2121 Make request property public on ParametersContainer
  Sources/Vapor/Routing/ParametersContainer.swift
Labels: enhancement

#2124 make client response codable
  Sources/Vapor/Client/ClientResponse.swift
  Sources/Vapor/HTTP/HTTPHeaders.swift
  Sources/Vapor/HTTP/HTTPStatus.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement

#2110 Update routing to include Route & implement Swift-Metrics
  Package.swift
  Sources/Vapor/Exports.swift
  Sources/Vapor/HTTP/ApplicationResponder.swift
  Sources/Vapor/Request/Request.swift
Labels: enhancement

#2125 Load .env on app init
  Sources/Vapor/Application.swift
Labels: bug

#2126 Vapor 4.0.0 Beta 3
  Package.swift
Labels: enhancement, semver-major

#2132 Fix HTTP request decoder race
  Package.swift
  Sources/Vapor/Request/Request+BodyStream.swift
  Sources/Vapor/Server/HTTPServerRequestDecoder.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: bug, semver-minor
