Repository vapor/vapor, pull requests merged in 2020-06, with the labels that each got.

#2369 Add support for PartialRangeUpTo in validators
  Sources/Vapor/Validation/Validators/Count.swift
  Sources/Vapor/Validation/Validators/Range.swift
  Tests/VaporTests/ValidationTests.swift
Labels: enhancement, semver-minor

#2387 Add the new stable 5.2 runner images to CI
  .github/workflows/test.yml
Labels: enhancement

#2397 Rename CORSMiddleware allowable origins case
  Sources/Vapor/Deprecations/CORSMiddleware+AllowOriginSetting.swift
  Sources/Vapor/Middleware/CORSMiddleware.swift
Labels: enhancement, semver-minor

#2400 Abort and StackTrace improvements
  .github/workflows/test.yml
  Sources/Vapor/Error/Abort.swift
  Sources/Vapor/Error/StackTrace.swift
  Tests/VaporTests/ErrorTests.swift
Labels: enhancement, semver-minor

#2405 Fix warnings in Xcode 12
  Sources/Development/routes.swift
  Sources/Vapor/Utilities/Base32.swift
  Sources/XCTVapor/XCTApplication.swift
  Sources/XCTVapor/XCTHTTPResponse.swift
  Tests/VaporTests/ErrorTests.swift
  Tests/VaporTests/PasswordTests.swift
  Tests/VaporTests/ValidationTests.swift
Labels: enhancement, semver-patch

#2399 Remove percent encoding when logging url path
  Sources/Vapor/Responder/DefaultResponder.swift
Labels: semver-patch

#2382 Follow the 'required' argument for nested validations
  Sources/Vapor/Validation/Validation.swift
  Tests/VaporTests/ValidationTests.swift
Labels: semver-patch

#2404 HTTP streaming improvements
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Sources/Vapor/HTTP/Server/HTTPServerHandler.swift
  Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
  Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
  Sources/Vapor/Request/Request+Body.swift
  Sources/Vapor/Request/Request+BodyStream.swift
  Sources/Vapor/Response/Response+Body.swift
  Sources/Vapor/Response/Response.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/PipelineTests.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/Utilities/TestLogging.swift
Labels: bug, semver-minor

#2366 Fix `routes` command symbol usage
  Sources/Vapor/Commands/RoutesCommand.swift
Labels: bug, semver-patch

#2354 Add case-insensitive routing
  Sources/Vapor/Responder/DefaultResponder.swift
  Sources/Vapor/Routing/Routes.swift
  Tests/VaporTests/RouteTests.swift
Labels: enhancement, semver-minor

#2411 Fix #file usage for 5.3
  Sources/XCTVapor/XCTApplication.swift
  Sources/XCTVapor/XCTHTTPResponse.swift
  Tests/VaporTests/ErrorTests.swift
  Tests/VaporTests/PasswordTests.swift
  Tests/VaporTests/ValidationTests.swift
Labels: bug, semver-patch

#2412 Logging improvements
  Sources/Development/routes.swift
  Sources/Vapor/Authentication/AuthenticationCache.swift
  Sources/Vapor/Authentication/Authenticator.swift
  Sources/Vapor/Error/AbortError.swift
  Sources/Vapor/Error/DebuggableError.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Sources/Vapor/Logging/Logger+Report.swift
  Sources/Vapor/Logging/LoggingSystem+Environment.swift
  Sources/Vapor/Request/Request.swift
  Sources/Vapor/Responder/DefaultResponder.swift
  Tests/VaporTests/ErrorTests.swift
Labels: enhancement, semver-minor

#2413 Immediate body streaming
  Sources/Development/routes.swift
  Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
  Sources/Vapor/Request/Request+BodyStream.swift
  Tests/VaporTests/PipelineTests.swift
Labels: enhancement, semver-patch

#2373 Add Vapor 3 API shims
  Package.swift
  Sources/Development/routes.swift
  Sources/_Vapor3/Config.swift
  Sources/_Vapor3/Exports.swift
  Sources/_Vapor3/Future.swift
  Sources/_Vapor3/NIOServerConfig.swift
  Sources/_Vapor3/Promise.swift
  Sources/_Vapor3/Services.swift
Labels: enhancement, semver-minor
