Repository vapor/vapor, pull requests merged in 2020-03, with the labels that each got.

#2201 Improve error logging
  Sources/Development/routes.swift
  Sources/Vapor/Error/Abort.swift
  Sources/Vapor/Error/AbortError.swift
  Sources/Vapor/Logging/Logger+Report.swift
  Sources/Vapor/Middleware/ErrorMiddleware.swift
Labels: enhancement

#2180 Parse Arrays in Query without the need for Brackets
  Sources/Vapor/URLEncodedForm/URLEncodedFormCodingConfiguration.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormData.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormDataConvertible.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormEncoder.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormParser.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormSerializer.swift
  Sources/Vapor/URLEncodedForm/URLQueryFragmentConvertible.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: enhancement

#2204 Release Candidate 1
  .github/workflows/test.yml
  Package.swift
  README.md
  Sources/CMultipartParser/include/multipartparser.h
  Sources/CMultipartParser/multipartparser.c
  Sources/Vapor/Application.swift
  Sources/Vapor/Exports.swift
  Sources/Vapor/Multipart/FormDataDecoder+Content.swift
  Sources/Vapor/Multipart/FormDataDecoder.swift
  Sources/Vapor/Multipart/FormDataEncoder+Content.swift
  Sources/Vapor/Multipart/FormDataEncoder.swift
  Sources/Vapor/Multipart/MultipartError.swift
  Sources/Vapor/Multipart/MultipartParser.swift
  Sources/Vapor/Multipart/MultipartPart.swift
  Sources/Vapor/Multipart/MultipartPartConvertible.swift
  Sources/Vapor/Multipart/MultipartSerializer.swift
  Sources/Vapor/Multipart/Utilities.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormCodingConfiguration.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormData.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormEncoder.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormError.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormParser.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormSerializer.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/MultipartTests.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: enhancement

#2206 Add ByteBuffer.string helper to XCTVapor
  Sources/XCTVapor/Exports.swift
  Sources/XCTVapor/Utilities.swift
Labels: enhancement, semver-minor

#2209 Add Base32 APIs from Vapor 3's Crypto
  Package.swift
  Sources/CBase32/cbase32.c
  Sources/CBase32/cbase32.h
  Sources/CBase32/include/module.modulemap
  Sources/Vapor/Utilities/Base32.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement, semver-minor

#2205 AbortError identifier fix
  Sources/Vapor/Error/Abort.swift
Labels: bug

#2103 Remove unused Validations code
  Sources/Vapor/Validation/RangeResult.swift
  Sources/Vapor/Validation/Validator.swift
  Sources/Vapor/Validation/Validators/And.swift
  Sources/Vapor/Validation/Validators/CharacterSet.swift
  Sources/Vapor/Validation/Validators/Count.swift
  Sources/Vapor/Validation/Validators/Email.swift
  Sources/Vapor/Validation/Validators/Nil.swift
  Sources/Vapor/Validation/Validators/NilIgnoring.swift
  Sources/Vapor/Validation/Validators/Range.swift
Labels: enhancement, semver-major

#2216 add Storage to Request + Response, deprecate userInfo
  Sources/Vapor/Application.swift
  Sources/Vapor/Authentication/AuthenticationCache.swift
  Sources/Vapor/Deprecated.swift
  Sources/Vapor/Request/Request.swift
  Sources/Vapor/Response/Response.swift
  Sources/Vapor/Sessions/Request+Session.swift
  Sources/Vapor/Sessions/SessionsMiddleware.swift
Labels: enhancement, semver-minor

#2217 Remove unused Validator.Valid type
  Sources/Vapor/Validation/Validators/Valid.swift
Labels: bug, semver-patch

#2214 improve HTTP server compression configuration
  Sources/Vapor/Deprecated.swift
  Sources/Vapor/Exports.swift
  Sources/Vapor/Server/HTTPServer.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement, semver-minor

#2222 Collected request body drain .end
  Sources/Vapor/Request/Request+Body.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: bug, semver-patch

#2223 Percent decode FileMiddleware path + Response.Body.collect
  Sources/Vapor/Middleware/FileMiddleware.swift
  Sources/Vapor/Response/Response+Body.swift
  Sources/XCTVapor/XCTApplication.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/Utilities/foo bar.html
Labels: bug, semver-minor

#2224 Update to Metrics 2.0
  Package.swift
  Sources/Vapor/Exports.swift
  Sources/Vapor/Responder/DefaultResponder.swift
Labels: enhancement, semver-major

#2225 Fix .env parsing with no trailing newline
  Sources/Vapor/Utilities/DotEnv.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/DotEnvTests.swift
Labels: bug, semver-patch

#2215 Remove double quotes from cooke value
  Sources/Vapor/HTTP/HTTPCookies.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: bug, semver-patch

#2232 Expose initializer of Validator
  Sources/Vapor/Validation/Validator.swift
Labels: bug, semver-minor

#2195 Allow WebSocket maxFrameSize to be configured
  Sources/Vapor/Response/Response.swift
  Sources/Vapor/Routing/RoutesBuilder+WebSocket.swift
  Sources/Vapor/Server/HTTPServerUpgradeHandler.swift
Labels: enhancement, semver-minor

#2219 Reintroduce the Debugging types and their tests
  Sources/Development/routes.swift
  Sources/Vapor/Debugging/Debuggable.swift
  Sources/Vapor/Debugging/Demangler.swift
  Sources/Vapor/Error/Abort.swift
  Sources/Vapor/Error/AbortError.swift
  Sources/Vapor/Error/ErrorSource.swift
  Sources/Vapor/Logging/Logger+Report.swift
  Tests/VaporTests/DebuggingTests/FooError.swift
  Tests/VaporTests/DebuggingTests/FooErrorTests.swift
  Tests/VaporTests/DebuggingTests/GeneralTests.swift
  Tests/VaporTests/DebuggingTests/MinimumError.swift
  Tests/VaporTests/DebuggingTests/TestError.swift
  Tests/VaporTests/DebuggingTests/TraceableTests.swift
Labels: enhancement

#2249 Provide the hex encoding utilities on Sequences
  Sources/Vapor/Utilities/Bytes+Hex.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement, semver-minor

#2257 Use .output close mode for non-keepalive requests
  Sources/Vapor/Server/HTTPServerHandler.swift
Labels: bug, semver-patch

#2258 Close Request.BodyStream on malformed request
  Sources/Development/routes.swift
  Sources/Vapor/Request/Request+BodyStream.swift
  Sources/Vapor/Server/HTTPServer.swift
  Sources/Vapor/Server/HTTPServerRequestDecoder.swift
Labels: bug, semver-patch

#2261 Use non-deprecated configureHTTP2SecureUpgrade.
  Package.swift
  Sources/Vapor/Server/HTTPServer.swift
Labels: enhancement, semver-minor

#2262 Add macOS CI and use checkout@v2
  .github/workflows/test.yml
Labels: enhancement

#2237 HTTP forwarded and contentDisposition + parsing improvements
  Sources/Vapor/Authentication/BasicAuthorization.swift
  Sources/Vapor/Authentication/BearerAuthorization.swift
  Sources/Vapor/Deprecated.swift
  Sources/Vapor/HTTP/EndpointCache.swift
  Sources/Vapor/HTTP/HTTPCookies.swift
  Sources/Vapor/HTTP/HTTPHeaderCacheControl.swift
  Sources/Vapor/HTTP/HTTPHeaderExpires.swift
  Sources/Vapor/HTTP/HTTPHeaderLastModified.swift
  Sources/Vapor/HTTP/HTTPHeaderValue.swift
  Sources/Vapor/HTTP/HTTPHeaders+ContentDisposition.swift
  Sources/Vapor/HTTP/HTTPHeaders+Directive.swift
  Sources/Vapor/HTTP/HTTPHeaders+Forwarded.swift
  Sources/Vapor/HTTP/HTTPHeaders+Name.swift
  Sources/Vapor/HTTP/HTTPHeaders.swift
  Sources/Vapor/HTTP/HTTPMediaType.swift
  Sources/Vapor/HTTP/HTTPMediaTypePreference.swift
  Sources/Vapor/Multipart/File+Multipart.swift
  Sources/Vapor/Request/Request.swift
  Sources/Vapor/Server/HTTPServerHandler.swift
  Sources/Vapor/Utilities/Collection+Safe.swift
  Sources/Vapor/Utilities/FileIO.swift
  Sources/Vapor/Utilities/SocketAddress+Hostname.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/AuthenticationTests.swift
  Tests/VaporTests/HTTPHeaderValueTests.swift
Labels: enhancement, semver-minor

#2239 Improve debugging
  Sources/Development/routes.swift
  Sources/Vapor/Error/Abort.swift
  Sources/Vapor/Error/AbortError.swift
  Sources/Vapor/Error/DebuggableError.swift
  Sources/Vapor/Error/Demangler.swift
  Sources/Vapor/Error/ErrorSource.swift
  Sources/Vapor/Error/StackTrace.swift
  Sources/Vapor/Logging/Logger+Report.swift
  Tests/VaporTests/ErrorTests.swift
Labels: enhancement, semver-minor

#2263 Install pkg-config is no longer needed
  .github/workflows/test.yml
Labels: enhancement

#2266 Support underscore in HTTP header directive key
  Sources/Vapor/HTTP/HTTPHeaders+Directive.swift
  Tests/VaporTests/HTTPHeaderTests.swift
Labels: bug, semver-patch

#2276 URL-encode dates using unix timestamp
  Sources/Vapor/URLEncodedForm/URLQueryFragmentConvertible.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: bug, semver-patch

#2260 update Authenticator protocol to return Void
  Sources/Vapor/Authentication/Authenticator.swift
  Sources/Vapor/Authentication/SessionAuthenticatable.swift
  Sources/Vapor/Deprecated.swift
  Sources/Vapor/Deprecated/Application+Request+UserInfo.swift
  Sources/Vapor/Deprecated/Authenticator+Middleware.swift
  Sources/Vapor/Deprecated/HTTPHeaders+firstValue.swift
  Sources/Vapor/Deprecated/HTTPServerConfiguration+supportCompression.swift
  Tests/VaporTests/AuthenticationTests.swift
Labels: bug, enhancement
