Repository vapor/vapor, pull requests merged in 2020-11, with the labels that each got.

#2520 Honor Configuration for Optional Date Decoding & Encoding
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormEncoder.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: semver-patch

#2521 Permit disabling automatic logging of all requests
  Sources/Vapor/Middleware/Application+Middleware.swift
  Sources/Vapor/Middleware/RouteLoggingMiddleware.swift
  Sources/Vapor/Responder/Application+Responder.swift
  Sources/Vapor/Responder/DefaultResponder.swift
Labels: enhancement, semver-minor

#2535 Rework 'SessionData' to be more friendly to 2nd party devs
  Sources/Vapor/Sessions/SessionData.swift
  Sources/Vapor/_Deprecations.swift
Labels: semver-minor
