Repository vapor/vapor, pull requests merged in 2020-09, with the labels that each got.

#2485 Fix Swift 5.3 trailing closure warnings
  Sources/XCTVapor/XCTApplication.swift
Labels: enhancement, semver-patch

#2495 Default cookie's SameSite attribute to lax
  Sources/Vapor/HTTP/Headers/HTTPCookies.swift
  Sources/Vapor/Sessions/SessionsConfiguration.swift
  Tests/VaporTests/HTTPHeaderTests.swift
Labels: semver-patch

#2500 Fix relative percent decoding in FileMiddleware
  Sources/Vapor/Middleware/FileMiddleware.swift
  Tests/VaporTests/FileTests.swift
  Tests/VaporTests/Utilities/foo.txt
Labels: bug, semver-patch
