Repository vapor/vapor, pull requests merged in 2020-01, with the labels that each got.

#2150 req.query.decode fix + test res.content.decode added
  Sources/Vapor/Application.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Sources/XCTVapor/XCTHTTPResponse.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement, semver-minor

#2151 Add swift-backtrace
  Package.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Exports.swift
Labels: enhancement, semver-minor

#2137 Add EventLoopGroupProvider
  Sources/Vapor/Application.swift
Labels: enhancement

#2152 Improve Validation Errors
  Sources/Vapor/Error/AbortError.swift
  Sources/Vapor/Validation/Validation.swift
  Sources/Vapor/Validation/ValidationsError.swift
  Sources/Vapor/Validation/ValidatorResult.swift
  Sources/Vapor/Validation/Validators/In.swift
  Sources/Vapor/Validation/Validators/Nil.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: bug, enhancement, semver-patch

#2153 Smal Auth/c Patch
  Sources/Vapor/Authentication/Authenticator.swift
  Sources/Vapor/Utilities/Array+Random.swift
Labels: enhancement

#2157 Add LOG_LEVEL Environment Variable
  Sources/Vapor/Logging/LoggingSystem+Environment.swift
Labels: enhancement, semver-patch

#2159 Environment-Specific DotEnv Files
  Sources/Development/configure.swift
  Sources/Development/main.swift
  Sources/Vapor/Application.swift
Labels: enhancement

#2163 Prevent a crash when decoding a single value from the query container
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: bug, semver-patch
