Repository vapor/vapor, pull requests merged in 2020-07, with the labels that each got.

#2364 Support a closure for instantiating RedirectMiddleware
  Sources/Vapor/Authentication/RedirectMiddleware.swift
  Tests/VaporTests/AuthenticationTests.swift
Labels: enhancement, semver-minor

#2431 Fix NIOSSL warning
  Package.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
Labels: enhancement, semver-patch

#2384 Fix for decoding percent escaped query keys (#2383)
  Sources/Vapor/URLEncodedForm/URLEncodedFormParser.swift
  Tests/VaporTests/QueryTests.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: enhancement

#2432 Percent-encoded brackets in query strings
  Sources/Vapor/URLEncodedForm/URLEncodedFormError.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormParser.swift
  Tests/VaporTests/QueryTests.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: bug, enhancement, semver-patch

#2396 add github action for automating api-docs
  .github/workflows/api-docs.yml
Labels: enhancement

#2437 Add provider tests to CI
  .github/workflows/test.yml
Labels: enhancement

#2438 Fix query content hooks
  Sources/Vapor/Content/URLQueryContainer.swift
  Tests/VaporTests/ContentTests.swift
Labels: bug, semver-minor

#2348 Add method for customizing log handler
  Sources/Vapor/Logging/LoggingSystem+Environment.swift
Labels: enhancement, semver-minor

#2420 Add non-variadic variants of RoutesBuilder group methods.
  Sources/Vapor/Routing/RoutesBuilder+Group.swift
Labels: enhancement, semver-minor

#2403 Allow XCTAssertContent to rethrow errors
  Sources/XCTVapor/XCTHTTPResponse.swift
Labels: enhancement, semver-minor

#2402 Add require(_:) extension to Parameters.
  Sources/Vapor/Routing/Parameters+Require.swift
  Tests/VaporTests/RouteTests.swift
Labels: enhancement, semver-minor

#2440 Add test timeouts
  .github/workflows/test.yml
Labels: enhancement

#2441 Header directive parameter quoting
  Sources/Vapor/HTTP/Headers/HTTPHeaders+Directive.swift
  Tests/VaporTests/HTTPHeaderTests.swift
Labels: bug, semver-patch

#2443 Add custom validation response example
  Sources/Vapor/Validation/ValidatorResult.swift
  Sources/Vapor/Validation/Validators/Case.swift
  Sources/Vapor/Validation/Validators/URL.swift
  Tests/VaporTests/Utilities/TestLogging.swift
  Tests/VaporTests/ValidationTests.swift
Labels: enhancement, semver-minor

#2425 Update body stream route example with error propagation
  Sources/Development/routes.swift
Labels: enhancement

#2419 Add validate(query:) method to Validatable protocol
  Sources/Vapor/Deprecations/Validatable+validate.swift
  Sources/Vapor/Validation/Validatable.swift
  Sources/Vapor/Validation/Validations.swift
  Tests/VaporTests/RouteTests.swift
  Tests/VaporTests/ValidationTests.swift
Labels: enhancement, semver-minor

#2442 Add support for string interpolation to URI
  Sources/Vapor/Utilities/URI.swift
  Tests/VaporTests/RequestTests.swift
Labels: enhancement, semver-minor

#2418 Add FileIO.writeFile
  Sources/Vapor/Utilities/FileIO.swift
  Tests/VaporTests/FileTests.swift
Labels: enhancement, semver-minor

#2435 Fix misspelled property name of class Routes
  Sources/Vapor/Deprecations/Routes+caseInsenstive.swift
  Sources/Vapor/Responder/DefaultResponder.swift
  Sources/Vapor/Routing/Routes.swift
  Tests/VaporTests/RouteTests.swift
Labels: bug, semver-minor

#2445 Add webSocket route overload with array path
  Sources/Vapor/Routing/RoutesBuilder+WebSocket.swift
Labels: enhancement, semver-minor

#2447 Fix array out of bounds error in StackTrace
  Sources/Vapor/Error/StackTrace.swift
Labels: bug, semver-patch

#2446 Make req.auth.require discardable
  Sources/Vapor/Authentication/AuthenticationCache.swift
Labels: enhancement, semver-patch

#2448 Allow setting hostname for testable application
  Sources/XCTVapor/XCTApplication.swift
  Tests/VaporTests/RequestTests.swift
Labels: enhancement, semver-minor

#2452 Fix Xcode 12 beta 3 warnings
  .github/workflows/test.yml
  Package.swift
  Sources/Development/routes.swift
  Sources/Vapor/Responder/DefaultResponder.swift
  Sources/XCTVapor/XCTHTTPResponse.swift
  Tests/VaporTests/ValidationTests.swift
Labels: bug, semver-patch
