Repository vapor/vapor, pull requests merged in 2020-10, with the labels that each got.

#2497 Add static dotenv loading function that can be used outside of Application
  Sources/Vapor/Application.swift
  Sources/Vapor/Utilities/DotEnv.swift
Labels: enhancement, semver-minor

#2499 OTP implementation
  Sources/Vapor/Security/OTP.swift
  Tests/VaporTests/SecurityTests.swift
Labels: enhancement, semver-minor

#2473 Array validation
  Sources/Vapor/Validation/Validation.swift
  Sources/Vapor/Validation/Validations.swift
  Sources/Vapor/Validation/ValidatorResult.swift
  Tests/VaporTests/ValidationTests.swift
Labels: enhancement, semver-minor

#2514 Make sure parameters passed to DotEnv load method are used
  Sources/Vapor/Utilities/DotEnv.swift
Labels: semver-patch

#2487 Provide option to implement `shouldUpgrade` on webSockets
  Sources/Vapor/HTTP/Server/HTTPServerUpgradeHandler.swift
  Sources/Vapor/Response/Response.swift
  Sources/Vapor/Routing/RoutesBuilder+WebSocket.swift
  Tests/VaporTests/RouteTests.swift
Labels: enhancement, semver-minor

#2517 Reuse the application's event loop group and thread pool when loading .env files
  Sources/Vapor/Application.swift
  Sources/Vapor/Deprecations/DotEnvFile+load.swift
  Sources/Vapor/Utilities/DotEnv.swift
Labels: semver-minor

#2519 Completely redefine how the CI for all Vapor repos works
  .github/workflows/test.yml
Labels: enhancement
