Repository vapor/vapor, pull requests merged in 2020-05, with the labels that each got.

#2312 Default max body size for streaming request body collection
  Sources/Vapor/Routing/Routes.swift
  Sources/Vapor/Routing/RoutesBuilder+Group.swift
  Sources/Vapor/Routing/RoutesBuilder+Method.swift
  Sources/Vapor/Utilities/ByteCount.swift
  Tests/VaporTests/RouteTests.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/UtilityTests.swift
Labels: enhancement, semver-minor

#2347 Fix invalid session ID handling
  Sources/Vapor/Sessions/SessionsMiddleware.swift
  Tests/VaporTests/SessionTests.swift
Labels: bug, semver-patch

#2365 New works-for-everything CI
  .github/workflows/test.yml
Labels: enhancement

#2353 `Environment` cleanups
  Sources/Vapor/Environment/Environment+Process.swift
  Sources/Vapor/Environment/Environment+Secret.swift
  Sources/Vapor/Environment/Environment.swift
  Sources/Vapor/Logging/LoggingSystem+Environment.swift
Labels: enhancement, semver-minor

#2357 Refactor request body streaming state handling
  Sources/Development/routes.swift
  Sources/Vapor/HTTP/BodyStream.swift
  Sources/Vapor/HTTP/Server/HTTPServerHandler.swift
  Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
  Sources/Vapor/Request/Request+BodyStream.swift
  Tests/VaporTests/BodyStreamStateTests.swift
  Tests/VaporTests/ServerTests.swift
Labels: bug, enhancement, semver-minor

#2372 Support periods in cookie names
  Sources/Vapor/HTTP/Headers/HTTPHeaders+Directive.swift
  Tests/VaporTests/HTTPHeaderTests.swift
Labels: bug, semver-patch

#2377 CentOS8 and AmazonLinux2 images come with zlib-devel now
  .github/workflows/test.yml
Labels: enhancement
