Repository vapor/vapor, pull requests merged in 2020-02, with the labels that each got.

#2165 Namespace Internal http_parser.c Symbols
  Sources/CURLParser/include/urlparser.h
  Sources/CURLParser/urlparser.c
  Sources/Development/configure.swift
  Sources/Development/main.swift
Labels: bug, semver-patch

#2173 Update due to vulnerability in NIO
  Package.swift
Labels: semver-patch

#2174 Require secure versions of Swift NIO SSL + HTTP/2
  Package.swift
Labels: semver-patch

#2155 Add .valid for decoding only validation
  Sources/Vapor/Validation/Validations.swift
  Sources/Vapor/Validation/Validators/Valid.swift
  Tests/VaporTests/ValidationTests.swift
Labels: enhancement, semver-minor

#2127 Make RFC1123 formatter use en_US_POSIX locale
  Sources/Vapor/Utilities/RFC1123.swift
Labels: enhancement, semver-patch

#2179 Remove the unused storage lock
  Sources/Vapor/Utilities/Storage.swift
Labels: bug

#2177 Remove fatalErrors from URLEncodedFormDecoder
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: bug, semver-patch

#2178 Reorganise a bit of code in URLEncodedFormParser to remove a fatalError
  Sources/Vapor/URLEncodedForm/URLEncodedFormParser.swift
Labels: enhancement

#2168 Adds CacheControl and Expires helpers to HTTPHeaders
  Sources/Vapor/HTTP/HTTPHeaderCacheControl.swift
  Sources/Vapor/HTTP/HTTPHeaderExpires.swift
  Sources/Vapor/HTTP/HTTPHeaders+Cache.swift
  Tests/VaporTests/CacheTests.swift
Labels: enhancement, semver-minor

#2182 Adds HTTPHeaders.LastModified
  Sources/Vapor/HTTP/HTTPHeaderExpires.swift
  Sources/Vapor/HTTP/HTTPHeaderLastModified.swift
Labels: enhancement, semver-minor

#2185 Add Application.Responder for configuring responder
  Sources/Vapor/Application.swift
  Sources/Vapor/Responder/Application+Responder.swift
  Sources/Vapor/Responder/DefaultResponder.swift
  Sources/Vapor/Server/Application+Server.swift
  Sources/Vapor/Sessions/Application+Sessions.swift
  circle.yml
Labels: enhancement, semver-minor

#2170 Log the request path of a failed request in the ErrorMiddleware.
  Sources/Vapor/Logging/Logger+LogError.swift
  Sources/Vapor/Middleware/ErrorMiddleware.swift
  Tests/LinuxMain.swift
  Tests/VaporTests/LoggingTests.swift
  Tests/VaporTests/LoggingTestsMocks.swift
Labels: enhancement

#2184 Adds EndpointCache for handling GET resource caching
  Sources/Vapor/HTTP/EndpointCache.swift
  Sources/Vapor/HTTP/HTTPHeaderCacheControl.swift
  Sources/Vapor/Responder/Application+Responder.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement, semver-minor

#2189 expose methods for hex encoded strings
  Sources/Vapor/Utilities/Bytes+Hex.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement, semver-minor

#2172 Adds case(of:) Validation
  Sources/Vapor/Validation/Validators/Case.swift
  Tests/VaporTests/ValidationTests.swift
Labels: enhancement, semver-minor

#2190 Load Environment variables from files
  Sources/Development/routes.swift
  Sources/Vapor/Services/Environment+Secret.swift
  Tests/VaporTests/EnvironmentSecretTests.swift
  Tests/VaporTests/Utilities/my-secret-env-content
Labels: enhancement, semver-minor

#2192 set HTTP request decompression ratio limit
  Sources/Vapor/Server/HTTPServer.swift
Labels: enhancement, semver-patch

#2198 Adds missing overloaded get method with [PathComponent] for the path parameter in the RoutesBuilder
  Sources/Vapor/Routing/RoutesBuilder+Method.swift
Labels: semver-minor

#2166 Migrate the crypto library to Swift Crypto
  Package.swift
  Sources/Vapor/Exports.swift
Labels: enhancement, semver-major

#2203 Make HTTP decompression limit configurable
  Sources/Vapor/Server/HTTPServer.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: enhancement, semver-minor

#2193 Improve error handling and timeouts for WebSockets
  Package.swift
  Sources/Vapor/Server/HTTPServerUpgradeHandler.swift
Labels: enhancement, semver-patch
