Repository vapor/vapor, pull requests merged in 2020-04, with the labels that each got.

#2275 Make testing with password easier with Password Service
  Sources/Vapor/Application.swift
  Sources/Vapor/Authentication/Application+PasswordService.swift
  Sources/Vapor/Authentication/PasswordService.swift
  Sources/Vapor/Authentication/PasswordVerifier.swift
  Sources/Vapor/Authentication/PlaintextVerifier.swift
  Sources/Vapor/Bcrypt/Bcrypt.swift
  Tests/VaporTests/BcryptTests.swift
Labels: enhancement

#2279 Allow Client to be Changed
  Sources/Vapor/Application.swift
  Sources/Vapor/Client/Application+Client.swift
  Sources/Vapor/Client/AsyncHTTPClient.swift
  Sources/Vapor/Client/Client.swift
  Sources/Vapor/Client/Request+Client.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/ClientTests.swift
Labels: enhancement

#2148 Allow nested route building to throw and rethrow
  Sources/Vapor/Routing/RoutesBuilder+Group.swift
  Sources/Vapor/Routing/RoutesBuilder+Middleware.swift
Labels: enhancement

#2053 AllowOriginSetting adjustments
  Sources/Vapor/Middleware/CORSMiddleware.swift
Labels: enhancement

#2290 Minor grammatical edits (GM Branch)
  Sources/Vapor/Environment/Environment+Process.swift
  Sources/Vapor/Environment/Environment+Secret.swift
  Sources/Vapor/Environment/Environment.swift
Labels: enhancement

#2296 Fix "Server starting on..." log message
  Sources/Vapor/HTTP/Server/HTTPServer.swift
Labels: bug, semver-patch

#2284 Async password verifier
  Sources/Vapor/Passwords/AsyncPasswordVerifier.swift
  Sources/Vapor/Passwords/PasswordVerifier.swift
  Sources/Vapor/Passwords/Request+Password.swift
  Tests/VaporTests/BcryptTests.swift
  Tests/VaporTests/PasswordTests.swift
Labels: enhancement

#2300 Change async password verifier to non-throwing
  Sources/Vapor/Passwords/AsyncPasswordHasher.swift
  Tests/VaporTests/PasswordTests.swift
Labels: bug, semver-patch

#2310 Improve body handling for HEAD responses
  Sources/Vapor/HTTP/Server/HTTPServerHandler.swift
  Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
  Sources/Vapor/Response/Response.swift
Labels: bug, semver-patch

#2315 Make Request.route publicly settable
  Sources/Vapor/Request/Request.swift
Labels: enhancement, semver-minor

#2267 Add Content hooks
  Sources/Vapor/Client/ClientRequest.swift
  Sources/Vapor/Client/ClientResponse.swift
  Sources/Vapor/Content/Content.swift
  Sources/Vapor/Content/ContentContainer.swift
  Sources/Vapor/Request/Request.swift
  Sources/Vapor/Response/Response.swift
  Sources/XCTVapor/XCTHTTPRequest.swift
  Sources/XCTVapor/XCTHTTPResponse.swift
  Tests/VaporTests/ContentTests.swift
Labels: enhancement, semver-minor

#2317 Support numbers in header directive keys
  Sources/Vapor/HTTP/Headers/HTTPHeaders+Directive.swift
  Tests/VaporTests/HTTPHeaderTests.swift
Labels: bug, semver-patch

#2314 Fix CORSMiddleware configuration initializer parameter
  Sources/Vapor/Deprecations/CORSMiddleware+Configuration+exposedHeaders.swift
  Sources/Vapor/Middleware/CORSMiddleware.swift
Labels: enhancement, semver-minor

#2326 HTTPMediaType comparisons should be case insensitive
  Sources/Vapor/HTTP/Headers/HTTPMediaType.swift
  Tests/VaporTests/HTTPHeaderTests.swift
Labels: enhancement, semver-patch

#2273 URLEncodedForm date encoding strategy
  Sources/Vapor/URLEncodedForm/DateFormatter+threadSpecific.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormEncoder.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: enhancement, semver-minor

#2335 Bump chosen Xcode version to latest
  .github/workflows/test.yml
Labels: bug

#2340 Use runIfActive instead of submit in async passwords
  Sources/Vapor/Passwords/AsyncPasswordHasher.swift
Labels: semver-patch
