Repository vapor/vapor, pull requests merged in 2020-08, with the labels that each got.

#2463 Fix decodeNil in URLEncodedFormDecoder's single value decoder
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Sources/Vapor/Utilities/BasicCodingKey.swift
  Tests/VaporTests/QueryTests.swift
Labels: bug, semver-patch

#2470 Update dependencies
  Package.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
  Tests/VaporTests/ServerTests.swift
Labels: enhancement, semver-patch

#2472 Server shutdown improvements
  Sources/Vapor/HTTP/Headers/HTTPHeaders+Connection.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Sources/Vapor/HTTP/Server/HTTPServerHandler.swift
  Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/WebSocketTests.swift
Labels: enhancement, semver-minor

#2238 Add missing validation for nested collections
  Sources/Vapor/Validation/Validation.swift
  Sources/Vapor/Validation/Validations.swift
  Sources/Vapor/Validation/ValidatorResult.swift
  Tests/VaporTests/ValidationTests.swift
Labels: enhancement

#2471 Support for Unix Domain Sockets
  Sources/Vapor/Commands/ServeCommand.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Sources/Vapor/Server/Server.swift
  Sources/Vapor/Utilities/URI.swift
  Sources/XCTVapor/XCTApplication.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/RequestTests.swift
  Tests/VaporTests/ServerTests.swift
Labels: enhancement, semver-minor

#2479 Fix crash related to setting nil hostname and port
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Tests/VaporTests/ServerTests.swift
Labels: semver-patch
