Repository vapor/vapor, pull requests merged in 2021-01, with the labels that each got.

#2342 Streaming files as partial content
  Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
  Sources/Vapor/Utilities/FileIO.swift
  Tests/VaporTests/HTTPHeaderTests.swift
Labels: enhancement, semver-minor

#2548 BUG FIX: Multipart/form-data crashed if data was missing
  Sources/Vapor/Multipart/FormDataDecoder.swift
  Tests/VaporTests/MultipartTests.swift
Labels: semver-patch

#2553 Extract multipart encoding/decoding from Vapor into MultipartKit
  Package.swift
  Sources/CMultipartParser/include/multipartparser.h
  Sources/CMultipartParser/multipartparser.c
  Sources/Vapor/Exports.swift
  Sources/Vapor/Multipart/FormDataDecoder.swift
  Sources/Vapor/Multipart/FormDataEncoder.swift
  Sources/Vapor/Multipart/MultipartError.swift
  Sources/Vapor/Multipart/MultipartParser.swift
  Sources/Vapor/Multipart/MultipartPart.swift
  Sources/Vapor/Multipart/MultipartPartConvertible.swift
  Sources/Vapor/Multipart/MultipartSerializer.swift
  Sources/Vapor/Multipart/Utilities.swift
  Tests/VaporTests/MultipartTests.swift
Labels: semver-patch

#2476 Hook up logging to HTTP Client
  Sources/Vapor/Client/Client.swift
  Sources/Vapor/Client/Request+Client.swift
  Sources/Vapor/HTTP/Client/Application+HTTP+Client.swift
  Sources/Vapor/HTTP/Client/EventLoopHTTPClient.swift
  Tests/VaporTests/ClientTests.swift
Labels: bug, enhancement, semver-minor

#2558 Add cache protocol
  Sources/Vapor/Application.swift
  Sources/Vapor/Cache/Application+Cache.swift
  Sources/Vapor/Cache/Cache.swift
  Sources/Vapor/Cache/MemoryCache.swift
  Sources/Vapor/Cache/Request+Cache.swift
  Tests/VaporTests/CacheTests.swift
  Tests/VaporTests/HTTPCacheTests.swift
Labels: enhancement, semver-minor

#2559 CORS: add "vary: origin" header if allowed origin is .originBased (#2539)
  Sources/Vapor/Middleware/CORSMiddleware.swift
  Tests/VaporTests/MiddlewareTests.swift
Labels: semver-patch

#2561 TOTP range now gives correct results (#2561)
  Sources/Vapor/Security/OTP.swift
  Tests/VaporTests/SecurityTests.swift
Labels: semver-patch
