Repository vapor/vapor, pull requests merged in 2021-11, with the labels that each got.

#2718 Fix issue where an invalid URL using the Client would crash
  Sources/Vapor/HTTP/Client/EventLoopHTTPClient.swift
  Tests/VaporTests/RouteTests.swift
Labels: semver-patch

#2726 Add missing async `send` version to `Client`
  Sources/Vapor/Concurrency/Client+Concurrency.swift
Labels: semver-minor

#2728 Add missing public access to HTTPHeaders.Link initializer
  Sources/Vapor/HTTP/Headers/HTTPHeaders+Link.swift
Labels: bug, semver-patch

#2725 Add a new test method to XCTApplicationTester returns a response directly
  Sources/XCTVapor/XCTApplication.swift
Labels: semver-patch

#2733 HTTP Authorization header scheme is case-insensitive
  Sources/Vapor/Authentication/BasicAuthorization.swift
  Sources/Vapor/Authentication/BearerAuthorization.swift
  Tests/AsyncTests/AsyncAuthTests.swift
  Tests/VaporTests/AuthenticationTests.swift
Labels: semver-patch

#2737 Filled in missing documentation in commonly used APIs
  Sources/Vapor/Application.swift
  Sources/Vapor/Bcrypt/Bcrypt.swift
  Sources/Vapor/Request/Request.swift
Labels: no-release-needed

#2730 Fix empty password in basic authorization parsing
  Sources/Vapor/Authentication/BasicAuthorization.swift
  Tests/VaporTests/AuthenticationTests.swift
Labels: semver-patch

#2732 fixed Request Body description
  Sources/Vapor/Request/Request+Body.swift
Labels: semver-patch

#2740 Add definition for application/json-seq
  .github/workflows/test.yml
  Sources/Vapor/HTTP/Headers/HTTPHeaders.swift
  Sources/Vapor/HTTP/Headers/HTTPMediaType.swift
Labels: enhancement, semver-minor
