Repository vapor/vapor, pull requests merged in 2022-11, with the labels that each got.

#2903 Update CI for 5.7, add API breakage check
  .github/workflows/test.yml
Labels: no-release-needed

#2895 Conforms `Request.Body` to `AsyncSequence`
  Sources/Vapor/Concurrency/Request+Concurrency.swift
  Tests/AsyncTests/AsyncRequestTests.swift
Labels: semver-minor

#2904 Fix 24h timeformat for `expire` and `last-modified` header
  Sources/Vapor/HTTP/Headers/HTTPHeaderExpires.swift
  Sources/Vapor/HTTP/Headers/HTTPHeaderLastModified.swift
  Tests/VaporTests/HTTPCacheTests.swift
  Tests/VaporTests/HTTPHeaderTests.swift
Labels: semver-patch

#2907 Fix unused generator parameter in Array.random(count:using:)
  Sources/Vapor/Utilities/Array+Random.swift
Labels: semver-patch

#2905 Fix Stream Callback never being called in close
  Sources/Vapor/HTTP/Server/HTTPServerHandler.swift
  Tests/VaporTests/ServerTests.swift
Labels: semver-patch

#2914 Fix encoding/decoding an array of dates with URL Encoding
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormEncoder.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: semver-patch
