Repository vapor/vapor, pull requests merged in 2022-01, with the labels that each got.

#2756 Update `Response` inline comments
  Sources/Vapor/Response/Response.swift
  Sources/Vapor/Response/ResponseCodable.swift
Labels: no-release-needed

#2759 Clean fix for backpressure
  Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
Labels: bug, semver-patch

#2765 Update ContentContainer.swift
  Sources/Vapor/Content/ContentContainer.swift
Labels: no-release-needed

#2762 Make Middlewares.resolve public
  Sources/Vapor/Middleware/MiddlewareConfiguration.swift
Labels: no-release-needed

#2761 Make `HTTPServer.init` and `Middleware.resolve` public
  Sources/Vapor/HTTP/Server/HTTPServer.swift
Labels: semver-minor

#2770 Add convenience methods for sending `Client` requests with a `Content` body
  Sources/Vapor/Client/Client.swift
  Sources/Vapor/Concurrency/Client+Concurrency.swift
  Tests/VaporTests/ClientTests.swift
Labels: semver-minor
