Repository vapor/vapor, pull requests merged in 2022-08, with the labels that each got.

#2865 Implement support for custom verify callbacks
  Package.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/Utilities/expired.crt
  Tests/VaporTests/Utilities/expired.key
Labels: semver-minor

#2875 Fix Leaf Downstream CI
  .github/workflows/test.yml
Labels: no-release-needed

#2874 Add missing protocol `ExpressibleByStringLiteral` to `HTTPHeaders.Name`
  Sources/Vapor/HTTP/Headers/HTTPHeaders+Name.swift
Labels: semver-patch

#2876 Update comment in DebuggableError.swift
  Sources/Vapor/Error/DebuggableError.swift
Labels: no-release-needed
