Repository vapor/vapor, pull requests merged in 2022-03, with the labels that each got.

#2780 Add project board workflow for good first issues
  .github/workflows/projectboard.yml
Labels: no-release-needed

#2773 Bump AsyncHTTPClient to 1.8.2
  Package.swift
Labels: semver-patch

#2784 Require version of swift-nio-http2 with security fix
  Package.swift
Labels: bug, semver-patch

#2764 Update Server Configuration after start
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: semver-patch

#2787 test that basic backpressure works
  Package.swift
  Tests/VaporTests/ServerTests.swift
Labels: no-release-needed

#2788 testRequestBodyBackpressureWorks: forgot one assert
  Tests/VaporTests/ServerTests.swift
Labels: no-release-needed

#2791 Update outdated middleware comments
  Sources/Vapor/Middleware/MiddlewareConfiguration.swift
  Sources/Vapor/Sessions/Request+Session.swift
  Sources/Vapor/Sessions/SessionsMiddleware.swift
Labels: no-release-needed

#2798 Updated name of .guardAuthMiddleware for Vapor 4
  Sources/Vapor/Authentication/GuardMiddleware.swift
Labels: no-release-needed
