Repository vapor/vapor, pull requests merged in 2022-10, with the labels that each got.

#2897 Fixed HTTP Decompression Test Failures
  Tests/VaporTests/ServerTests.swift
Labels: no-release-needed

#2894 Prevent vapor from crashing during a crash in third-party code, obfuscating the real problem
  Sources/Vapor/Application.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: semver-minor

#2891 Migrate from `Lock` to `NIOLock`
  Package.swift
  Sources/Development/configure.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Cache/MemoryCache.swift
  Sources/Vapor/HTTP/EndpointCache.swift
  Tests/VaporTests/Utilities/CapturingMetricsSystem.swift
  Tests/VaporTests/Utilities/ThreadSafe.swift
  Tests/VaporTests/WebSocketTests.swift
Labels: semver-patch
