Repository vapor/vapor, pull requests merged in 2022-04, with the labels that each got.

#2801 Add MacStadium logo for the free build machine
  README.md
Labels: no-release-needed

#2797 Fix ambiguous error with Swift nightlies
  Sources/Vapor/HTTP/Headers/HTTPHeaders+Directive.swift
Labels: semver-patch

#2804 Added custom failure descriptions to Validation Errors
  Sources/Vapor/Validation/Validation.swift
  Sources/Vapor/Validation/Validations.swift
  Sources/Vapor/Validation/ValidationsError.swift
  Tests/VaporTests/ValidationTests.swift
Labels: semver-minor

#2805 Provide async closures in XCTVapor
  Sources/XCTVapor/XCTApplication.swift
Labels: semver-minor
