Repository vapor/vapor, pull requests merged in 2022-07, with the labels that each got.

#2855 Fix CredentialsAuthenticator not receiving all the body
  Sources/Vapor/Authentication/Authenticator.swift
Labels: semver-patch

#2859 fix: validate each not taking required parameter into account
  Sources/Vapor/Validation/Validation.swift
  Tests/VaporTests/ValidationTests.swift
Labels: semver-patch

#2857 Add documentation comments and a defaulting subscript to `Storage`.
  Sources/Vapor/Utilities/Storage.swift
Labels: enhancement, semver-minor

#2856 Add support for regular expression validations
  Sources/Vapor/Validation/Validators/Pattern.swift
  Tests/VaporTests/ValidationTests.swift
Labels: semver-minor
