Repository vapor/vapor, pull requests merged in 2023-12, with the labels that each got.

#3109 Bring back AsyncCommands
  Package.swift
  Package@swift-5.9.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Core/Core.swift
  Tests/AsyncTests/AsyncCommandsTests.swift
Labels: semver-minor

#3114 Add fully async entrypoints
  .github/dependabot.yml
  Package.swift
  Package@swift-5.9.swift
  Sources/Development/entrypoint.swift
  Sources/Vapor/Application.swift
  Tests/AsyncTests/AsyncClientTests.swift
  Tests/AsyncTests/AsyncWebSocketTests.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/PipelineTests.swift
Labels: semver-minor

#3116 Fix encoding and decoding of HTTPHeaders
  Sources/Vapor/HTTP/Headers/HTTPHeaders.swift
  Tests/VaporTests/HTTPHeaderTests.swift
Labels: bug, semver-patch

#3117 Consistently use the value from `X-Request-Id` as the request's ID when present
  Sources/Vapor/Request/Request.swift
  Tests/VaporTests/RequestTests.swift
Labels: semver-patch

#3113 Fix setting public folder for `FileMiddleware` when using bundles
  Sources/Vapor/Middleware/FileMiddleware.swift
  Tests/VaporTests/MiddlewareTests.swift
Labels: bug, semver-patch
