Repository vapor/vapor, pull requests merged in 2023-03, with the labels that each got.

#2935 FileMiddleware redirect option
  Sources/Vapor/Middleware/FileMiddleware.swift
  Tests/VaporTests/FileTests.swift
Labels: semver-minor

#2973 Revise api doc
  Sources/Vapor/Concurrency/FileIO+Concurrency.swift
Labels: no-release-needed

#2969 Better `DecodingError` description
  Sources/Vapor/Error/AbortError.swift
  Tests/VaporTests/ContentTests.swift
Labels: semver-patch

#2975 Fix imports
  Sources/Vapor/Concurrency/WebSocket+Concurrency.swift
  Sources/Vapor/Routing/Request+WebSocket.swift
  Sources/Vapor/Routing/RoutesBuilder+WebSocket.swift
Labels: no-release-needed

#2934 Add 308 Redirect
  Sources/Vapor/Error/Abort.swift
  Sources/Vapor/Middleware/FileMiddleware.swift
  Sources/Vapor/Request/Redirect.swift
  Tests/VaporTests/RequestTests.swift
Labels: semver-minor

#2971 Add support for Cache-Control header 'immutable' attribute
  Sources/Vapor/HTTP/Headers/HTTPHeaderCacheControl.swift
  Tests/VaporTests/HTTPCacheTests.swift
  Tests/VaporTests/HTTPHeaderTests.swift
Labels: semver-patch

#2966 Correctly handle invalid numbers in range validations
  Sources/Vapor/Validation/RangeResult.swift
  Sources/Vapor/Validation/Validators/Range.swift
  Tests/VaporTests/ValidationTests.swift
Labels: semver-patch

#2987 Imports fixes
  Sources/Vapor/Multipart/FormDataDecoder+Content.swift
  Sources/Vapor/Multipart/FormDataEncoder+Content.swift
Labels: semver-patch
