Repository vapor/vapor, pull requests merged in 2023-11, with the labels that each got.

#3095 Remove Sendable requirements on Authenticatable
  Sources/Vapor/Authentication/AuthenticationCache.swift
  Sources/Vapor/Authentication/Authenticator.swift
  Sources/Vapor/Authentication/GuardMiddleware.swift
  Sources/Vapor/Authentication/RedirectMiddleware.swift
Labels: semver-patch

#3093 Make Request Sendable
  .gitignore
  Package.swift
  Package@swift-5.9.swift
  Sources/Development/routes.swift
  Sources/Vapor/Commands/ServeCommand.swift
  Sources/Vapor/Concurrency/Request+Concurrency.swift
  Sources/Vapor/Concurrency/RoutesBuilder+Concurrency.swift
  Sources/Vapor/Concurrency/WebSocket+Concurrency.swift
  Sources/Vapor/HTTP/Headers/HTTPCookies.swift
  Sources/Vapor/HTTP/Headers/HTTPMediaType.swift
  Sources/Vapor/HTTP/Server/HTTPServerHandler.swift
  Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
  Sources/Vapor/Request/Request+Body.swift
  Sources/Vapor/Request/Request.swift
  Sources/Vapor/Responder/DefaultResponder.swift
  Sources/Vapor/Routing/Route.swift
  Sources/Vapor/Routing/Routes.swift
  Sources/Vapor/Routing/RoutesBuilder+WebSocket.swift
  Sources/Vapor/Server/Server.swift
  Sources/Vapor/Sessions/MemorySessions.swift
  Sources/Vapor/Validation/Validators/CharacterSet.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/ServerTests.swift
Labels: semver-minor

#3098 Modernize sponsors automation workflow
  .github/workflows/sponsors.yml
Labels: enhancement, no-release-needed, github_actions

#3092 Create a thread pool of System.coreCount rather than 64 when initializing an Application
  Sources/Vapor/Core/Core.swift
Labels: bug, semver-patch

#3096 Make Async Request Body actually work
  NOTICES.txt
  Sources/Vapor/Concurrency/RequestBody+Concurrency.swift
  Sources/Vapor/Request/Request+BodyStream.swift
  Tests/AsyncTests/AsyncRequestTests.swift
Labels: semver-patch

#3106 Add public initializer for `XCTHTTPRequest`
  Sources/XCTVapor/XCTHTTPRequest.swift
Labels: enhancement, semver-minor
