Repository vapor/vapor, pull requests merged in 2023-01, with the labels that each got.

#2926 Enable back deployment of Concurrency
  Package.swift
  Sources/Development/routes.swift
  Sources/Vapor/Concurrency/AnyResponse+Concurrency.swift
  Sources/Vapor/Concurrency/AsyncBasicResponder.swift
  Sources/Vapor/Concurrency/AsyncMiddleware.swift
  Sources/Vapor/Concurrency/AsyncPasswordHasher+Concurrency.swift
  Sources/Vapor/Concurrency/AsyncSessionDriver.swift
  Sources/Vapor/Concurrency/Authentication+Concurrency.swift
  Sources/Vapor/Concurrency/Cache+Concurrency.swift
  Sources/Vapor/Concurrency/Client+Concurrency.swift
  Sources/Vapor/Concurrency/FileIO+Concurrency.swift
  Sources/Vapor/Concurrency/Request+Concurrency.swift
  Sources/Vapor/Concurrency/Responder+Concurrency.swift
  Sources/Vapor/Concurrency/ResponseCodable+Concurrency.swift
  Sources/Vapor/Concurrency/RoutesBuilder+Concurrency.swift
  Sources/Vapor/Concurrency/ViewRenderer+Concurrency.swift
  Sources/Vapor/Concurrency/WebSocket+Concurrency.swift
  Tests/AsyncTests/AsyncAuthTests.swift
  Tests/AsyncTests/AsyncCacheTests.swift
  Tests/AsyncTests/AsyncClientTests.swift
  Tests/AsyncTests/AsyncMiddlewareTests.swift
  Tests/AsyncTests/AsyncPasswordTests.swift
  Tests/AsyncTests/AsyncRequestTests.swift
  Tests/AsyncTests/AsyncRouteTests.swift
  Tests/AsyncTests/AsyncSessionTests.swift
  Tests/AsyncTests/AsyncWebSocketTests.swift
Labels: semver-minor

#2698 Allow URLEncodedForms to decode 'on' value als Bool => true
  Sources/Vapor/URLEncodedForm/URLQueryFragmentConvertible.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: semver-patch

#2940 Fix `.wait()` warning in tests
  Tests/AsyncTests/AsyncClientTests.swift
Labels: no-release-needed

#2943 Fix: FileIO headers
  Sources/Vapor/Utilities/FileIO.swift
Labels: semver-patch
