Repository vapor/vapor, pull requests merged in 2023-09, with the labels that each got.

#3064 The swift-backtrace library is no longer needed in 5.9
  Package@swift-5.9.swift
  Sources/Development/routes.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Error/Abort.swift
  Sources/Vapor/Error/DebuggableError.swift
  Sources/Vapor/Error/StackTrace.swift
  Sources/Vapor/Logging/LoggingSystem+Environment.swift
  Sources/Vapor/Responder/DefaultResponder.swift
  Tests/AsyncTests/AsyncMiddlewareTests.swift
  Tests/VaporTests/BcryptTests.swift
  Tests/VaporTests/ContentTests.swift
  Tests/VaporTests/ErrorTests.swift
  Tests/VaporTests/FileTests.swift
  Tests/VaporTests/HTTPHeaderTests.swift
  Tests/VaporTests/MetricsTests.swift
  Tests/VaporTests/MiddlewareTests.swift
  Tests/VaporTests/QueryTests.swift
  Tests/VaporTests/RouteTests.swift
  Tests/VaporTests/URLEncodedFormTests.swift
  Tests/VaporTests/Utilities/CapturingMetricsSystem.swift
Labels: semver-minor

#3068 `Logger.report()` should handle `LocalizedError`, `DecodingError`, and `EncodingError` identically to other errors
  .github/workflows/api-docs.yml
  .github/workflows/projectboard.yml
  .github/workflows/test.yml
  Sources/Vapor/Logging/Logger+Report.swift
Labels: bug, semver-patch

#3071 Remove hardcoded ports in tests
  Sources/XCTVapor/XCTApplication.swift
  Tests/AsyncTests/AsyncClientTests.swift
  Tests/AsyncTests/AsyncRouteTests.swift
  Tests/AsyncTests/AsyncWebSocketTests.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/FileTests.swift
  Tests/VaporTests/RequestTests.swift
  Tests/VaporTests/RouteTests.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/WebSocketTests.swift
Labels: no-release-needed

#3070 Add support for Swift Crypto 3.0.0
  Package.swift
Labels: semver-minor

#3073 Support Crypto 3.0.0 in the other package manifest
  Package@swift-5.9.swift
Labels: bug, semver-minor

#3072 Pass X-Request-Id if present
  Sources/Vapor/HTTP/Headers/HTTPHeaders+Name.swift
  Sources/Vapor/Request/Request.swift
  Tests/VaporTests/HTTPHeaderTests.swift
  Tests/VaporTests/RequestTests.swift
Labels: enhancement, semver-patch

#2922 HTTPServerErrorHandler: Improve Error Handling for HTTPParserError
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Tests/VaporTests/PipelineTests.swift
Labels: semver-patch

#3057 More Sendable Conformances
  Package.swift
  Package@swift-5.9.swift
  Sources/Development/routes.swift
  Sources/Vapor/Authentication/BasicAuthorization.swift
  Sources/Vapor/Authentication/BearerAuthorization.swift
  Sources/Vapor/Concurrency/ResponseCodable+Concurrency.swift
  Sources/Vapor/HTTP/BodyStream.swift
  Sources/Vapor/HTTP/Server/HTTPServerHandler.swift
  Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
  Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
  Sources/Vapor/HTTP/Server/HTTPServerUpgradeHandler.swift
  Sources/Vapor/Request/Request+Body.swift
  Sources/Vapor/Request/Request+BodyStream.swift
  Sources/Vapor/Request/Request.swift
  Sources/Vapor/Response/Response+Body.swift
  Sources/Vapor/Utilities/File.swift
  Sources/Vapor/Utilities/FileIO.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/CacheTests.swift
  Tests/VaporTests/ContentTests.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/SessionTests.swift
  Tests/VaporTests/Utilities/CapturingMetricsSystem.swift
Labels: semver-minor

#3074 Add numerous missing `@preconcurrency` attributes
  README.md
  Sources/Vapor/Cache/Application+Cache.swift
  Sources/Vapor/Client/Application+Clients.swift
  Sources/Vapor/HTTP/BasicResponder.swift
  Sources/Vapor/HTTP/Server/HTTPServerUpgradeHandler.swift
  Sources/Vapor/Middleware/ErrorMiddleware.swift
  Sources/Vapor/Passwords/Application+Passwords.swift
  Sources/Vapor/Request/Request+Body.swift
  Sources/Vapor/Responder/Application+Responder.swift
  Sources/Vapor/Routing/Request+WebSocket.swift
  Sources/Vapor/Server/Application+Servers.swift
  Sources/Vapor/Sessions/Application+Sessions.swift
  Sources/Vapor/Sessions/SessionsConfiguration.swift
  Sources/Vapor/Utilities/FileIO.swift
  Sources/Vapor/Utilities/Thread.swift
  Sources/Vapor/Validation/Validations.swift
  Sources/Vapor/Validation/Validator.swift
  Sources/Vapor/View/Application+Views.swift
  Sources/XCTVapor/XCTApplication.swift
Labels: semver-patch
