Repository vapor/vapor, pull requests merged in 2024-12, with the labels that each got.

#3264 Remove CodeQL checks from CI
  .github/workflows/test.yml
Labels: no-release-needed

#3265 Fix Concurrency Warnings and Deprecations
  Package.swift
  Sources/Vapor/Commands/RoutesCommand.swift
  Sources/Vapor/Concurrency/Cache+Concurrency.swift
  Sources/Vapor/Content/Content.swift
  Sources/Vapor/Middleware/ErrorMiddleware.swift
  Sources/Vapor/Responder/DefaultResponder.swift
  Sources/Vapor/Routing/Route.swift
  Sources/Vapor/View/View.swift
  Tests/VaporTests/AsyncCacheTests.swift
  Tests/VaporTests/AsyncRequestTests.swift
Labels: semver-minor

#2901 Make Services in Vapor Usable
  Sources/Vapor/Services/App+Service.swift
  Sources/Vapor/Services/Req+Service.swift
  Sources/Vapor/Services/Service.swift
  Tests/VaporTests/ServiceTests.swift
Labels: semver-minor

#3253 Adds swift-distributed-tracing and TracingMiddleware
  Package.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/HTTP/BasicResponder.swift
  Sources/Vapor/Middleware/Middleware.swift
  Sources/Vapor/Middleware/TracingMiddleware.swift
  Sources/Vapor/Request/Request.swift
  Sources/Vapor/Response/ResponseCodable.swift
  Sources/Vapor/Routing/RoutesBuilder+Method.swift
  Tests/VaporTests/MiddlewareTests.swift
  Tests/VaporTests/Utilities/TestTracer.swift
Labels: semver-minor

#3274 Minor swift-testing related improvements
  Sources/VaporTesting/VaporTestingContext.swift
  Sources/VaporTesting/withApp.swift
  Sources/XCTVapor/XCTVaporContext.swift
Labels: semver-patch

#3275 In withApp(), always shut down app even if error is thrown
  Sources/VaporTesting/withApp.swift
Labels: semver-patch

#3263 Validation API | `Custom` Validator
  Sources/Vapor/Validation/Validation.swift
  Sources/Vapor/Validation/Validators/Custom.swift
  Tests/VaporTests/ValidationTests.swift
Labels: semver-minor
