Repository vapor/vapor, pull requests merged in 2024-08, with the labels that each got.

#3220 Update awesome-vapor repository link.
  README.md
Labels: no-release-needed

#3216 HTTPHeaders.LastModified Public Initializer
  Sources/Vapor/HTTP/Headers/HTTPHeaderLastModified.swift
Labels: semver-minor

#3224 Use Configured JSONEncoder in ErrorMiddleware
  Sources/Vapor/Middleware/ErrorMiddleware.swift
  Tests/VaporTests/ErrorTests.swift
Labels: semver-patch

#3215 Conditional Content Response Compression
  Package.swift
  Package@swift-5.9.swift
  Sources/Vapor/HTTP/Headers/HTTPHeaders+Name.swift
  Sources/Vapor/HTTP/Headers/HTTPHeaders+ResponseCompression.swift
  Sources/Vapor/HTTP/Headers/HTTPMediaType.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Sources/Vapor/HTTP/Server/HTTPServerConfiguration+RequestDecompressionConfiguration.swift
  Sources/Vapor/HTTP/Server/HTTPServerConfiguration+ResponseCompressionConfiguration.swift
  Sources/Vapor/Middleware/ResponseCompressionMiddleware.swift
  Tests/VaporTests/ConditionalResponseCompressionTests.swift
  Tests/VaporTests/HTTPMediaTypeSetTests.swift
Labels: semver-minor
