Repository vapor/vapor, pull requests merged in 2024-04, with the labels that each got.

#3162 Fix typos across the codebase
  .github/contributing.md
  .github/maintainers.md
  Sources/Vapor/Authentication/AuthenticationCache.swift
  Sources/Vapor/Concurrency/RequestBody+Concurrency.swift
  Sources/Vapor/Content/ContentCoders.swift
  Sources/Vapor/Content/PlaintextEncoder.swift
  Sources/Vapor/Deprecations/DotEnvFile+load.swift
  Sources/Vapor/HTTP/Headers/HTTPCookies.swift
  Sources/Vapor/Request/Request.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormSerializer.swift
  Sources/Vapor/Utilities/BaseN.swift
  Sources/Vapor/Utilities/DotEnv.swift
  Sources/Vapor/Validation/RangeResult.swift
  Sources/Vapor/Validation/Validators/Range.swift
  Tests/VaporTests/AsyncMiddlewareTests.swift
  Tests/VaporTests/AsyncPasswordTests.swift
  Tests/VaporTests/AsyncRequestTests.swift
  Tests/VaporTests/MiddlewareTests.swift
  Tests/VaporTests/PasswordTests.swift
  Tests/VaporTests/RequestTests.swift
  Tests/VaporTests/Utilities/CapturingMetricsSystem.swift
Labels: enhancement, semver-patch

#3174 Don't set ignore status for SIGTERM and SIGINT on Linux
  Sources/Vapor/Commands/ServeCommand.swift
Labels: bug, semver-patch

#3126 HTTP2 Response Compression/Request Decompression
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Tests/VaporTests/ServerTests.swift
Labels: semver-patch

#3175 Enabled Request Decompression By Default
  Sources/Vapor/HTTP/Server/HTTPServer.swift
Labels: semver-patch

#3015 Advanced ETag Comparison now supported
  Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
  Sources/Vapor/Middleware/FileMiddleware.swift
  Sources/Vapor/Utilities/FileIO.swift
  Tests/VaporTests/FileTests.swift
Labels: semver-minor

#3147 Remove HeadResponder
  Sources/Vapor/Responder/DefaultResponder.swift
  Tests/VaporTests/RouteTests.swift
Labels: bug, semver-patch

#3177 Removed streamFile deprecation + deactivated advancedETagComparison by default
  Sources/Vapor/Middleware/FileMiddleware.swift
  Sources/Vapor/Utilities/FileIO.swift
Labels: semver-patch

#3167 Migrate to Async NIOFileIO APIs
  Package.swift
  Package@swift-5.9.swift
  Sources/Vapor/Concurrency/FileIO+Concurrency.swift
  Sources/Vapor/Utilities/FileIO.swift
  Tests/VaporTests/FileTests.swift
  Tests/VaporTests/Utilities/long-test-file.txt
Labels: semver-minor

#3178 Update provider tests to 5.10
  .github/workflows/test.yml
Labels: no-release-needed

#3160 Patch configuration and log actual port on startup
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/ServerTests.swift
Labels: semver-patch

#3181 Fix test when run in parallel
  Tests/VaporTests/ServerTests.swift
Labels: no-release-needed

#3182 Improve Parallel Testing
  .github/workflows/test.yml
  Package.swift
  Package@swift-5.9.swift
  Tests/VaporTests/FileTests.swift
Labels: no-release-needed

#2998 Add support for asynchronous body stream writing
  Sources/Vapor/HTTP/BodyStream.swift
  Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
  Sources/Vapor/Request/Request+BodyStream.swift
  Sources/Vapor/Response/Response+Body.swift
  Tests/VaporTests/PipelineTests.swift
Labels: semver-minor

#3183 Fix test failures
  Tests/VaporTests/PipelineTests.swift
Labels: no-release-needed
