Repository vapor/vapor, pull requests merged in 2024-09, with the labels that each got.

#3225 Support Swift 6
  Package.swift
  Package@swift-5.9.swift
  Sources/Vapor/Commands/ServeCommand.swift
  Sources/Vapor/Content/JSONCoders+Content.swift
  Sources/Vapor/Content/PlaintextDecoder.swift
  Sources/Vapor/Content/PlaintextEncoder.swift
  Sources/Vapor/HTTP/Headers/HTTPHeaderCacheControl.swift
  Sources/Vapor/Logging/LoggingSystem+Environment.swift
  Sources/Vapor/Sessions/MemorySessions.swift
  Sources/Vapor/Utilities/RFC1123.swift
  Sources/Vapor/Utilities/URI.swift
  Sources/Vapor/Validation/Validators/CharacterSet.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/ContentTests.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/URITests.swift
Labels: semver-minor

#3228 Add response order pipelining test
  Tests/VaporTests/PipelineTests.swift
Labels: no-release-needed

#3226 Throw an error if unkeyed container is at end
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Tests/VaporTests/QueryTests.swift
Labels: semver-patch

#3222 Raise error when the data expected an array but not parsed as array
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: semver-patch
