Repository vapor/vapor, pull requests merged in 2024-01, with the labels that each got.

#3128 Use `singleton` `EventLoopGroup`
  Package.swift
  Package@swift-5.9.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Concurrency/WebSocket+Concurrency.swift
  Sources/Vapor/Deprecations/DotEnvFile+load.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Sources/Vapor/Utilities/DotEnv.swift
  Sources/Vapor/View/PlaintextRenderer.swift
  Sources/XCTVapor/XCTApplication.swift
  Tests/AsyncTests/AsyncRequestTests.swift
  Tests/VaporTests/ServerTests.swift
Labels: semver-minor

#3131 Update routing-kit version
  Package.swift
  Package@swift-5.9.swift
Labels: enhancement, semver-patch

#3140 Fix broken URI behaviors
  README.md
  Sources/Vapor/Content/ContainerGetPathExecutor.swift
  Sources/Vapor/Content/ContentCoders.swift
  Sources/Vapor/Content/ContentContainer.swift
  Sources/Vapor/Content/JSONCoders+Content.swift
  Sources/Vapor/Content/PlaintextDecoder.swift
  Sources/Vapor/Content/PlaintextEncoder.swift
  Sources/Vapor/Content/URLQueryCoders.swift
  Sources/Vapor/Content/URLQueryContainer.swift
  Sources/Vapor/Multipart/FormDataDecoder+Content.swift
  Sources/Vapor/Multipart/FormDataEncoder+Content.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormEncoder.swift
  Sources/Vapor/Utilities/URI.swift
  Tests/AsyncTests/AsyncCommandsTests.swift
  Tests/AsyncTests/AsyncRequestTests.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/ContentTests.swift
  Tests/VaporTests/RouteTests.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/URITests.swift
Labels: bug, semver-minor

#3143 Fix URI handling with multiple slashes and variable components.
  Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
  Sources/Vapor/Utilities/URI.swift
  Sources/XCTVapor/XCTApplication.swift
  Sources/XCTVapor/XCTHTTPResponse.swift
  Tests/AsyncTests/AsyncPasswordTests.swift
  Tests/VaporTests/DotEnvTests.swift
  Tests/VaporTests/EnvironmentSecretTests.swift
  Tests/VaporTests/ErrorTests.swift
  Tests/VaporTests/FileTests.swift
  Tests/VaporTests/PasswordTests.swift
  Tests/VaporTests/RouteTests.swift
  Tests/VaporTests/ValidationTests.swift
Labels: semver-patch

#3141 Merge Async Tests
  Package.swift
  Package@swift-5.9.swift
  Tests/VaporTests/AsyncAuthTests.swift
  Tests/VaporTests/AsyncCacheTests.swift
  Tests/VaporTests/AsyncClientTests.swift
  Tests/VaporTests/AsyncCommandsTests.swift
  Tests/VaporTests/AsyncMiddlewareTests.swift
  Tests/VaporTests/AsyncPasswordTests.swift
  Tests/VaporTests/AsyncRequestTests.swift
  Tests/VaporTests/AsyncRouteTests.swift
  Tests/VaporTests/AsyncSessionTests.swift
  Tests/VaporTests/AsyncWebSocketTests.swift
  Tests/VaporTests/CacheTests.swift
  Tests/VaporTests/ClientTests.swift
Labels: no-release-needed
