Repository vapor/vapor, pull requests merged in 2024-06, with the labels that each got.

#3194 Adds TIFF and WebP HTTP Media Types
  Sources/Vapor/HTTP/Headers/HTTPMediaType.swift
Labels: semver-patch

#3164 Fix decoding 'flag' URL query params via `.decode(StructType.self)`
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Tests/VaporTests/QueryTests.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: semver-patch

#3206 Fixed an issue where response compression would fail when returning 304 Not Modified
  Package.swift
  Package@swift-5.9.swift
Labels: bug, semver-patch

#3208 Add Sendable conformance to XCTApplicationTester, XCTHTTPRequest/Response, and some others
  Sources/Vapor/Content/ContentCoders.swift
  Sources/Vapor/Content/ContentConfiguration.swift
  Sources/Vapor/Content/JSONCoders+Content.swift
  Sources/Vapor/Content/PlaintextEncoder.swift
  Sources/Vapor/Content/URLQueryCoders.swift
  Sources/Vapor/HTTP/Headers/HTTPHeaderCacheControl.swift
  Sources/Vapor/HTTP/Headers/HTTPHeaders+Name.swift
  Sources/Vapor/HTTP/Server/HTTPServerRequestDecoder.swift
  Sources/Vapor/Logging/LoggingSystem+Environment.swift
  Sources/Vapor/Routing/RoutesBuilder.swift
  Sources/Vapor/URLEncodedForm/DateFormatter+threadSpecific.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
  Sources/Vapor/URLEncodedForm/URLEncodedFormEncoder.swift
  Sources/Vapor/Utilities/RFC1123.swift
  Sources/XCTVapor/XCTApplication.swift
  Sources/XCTVapor/XCTHTTPRequest.swift
  Sources/XCTVapor/XCTHTTPResponse.swift
  Tests/VaporTests/BaseNTests.swift
  Tests/VaporTests/BodyStreamStateTests.swift
  Tests/VaporTests/URLEncodedFormTests.swift
  Tests/VaporTests/WebSocketTests.swift
Labels: semver-minor
