Repository vapor/vapor, pull requests merged in 2024-10, with the labels that each got.

#3240 Drop Support for Swift 5.8
  .github/workflows/test.yml
  Package.swift
  Package@swift-5.9.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Commands/ServeCommand.swift
  Sources/Vapor/Content/JSONCoders+Content.swift
  Sources/Vapor/Exports.swift
  Sources/Vapor/HTTP/EndpointCache.swift
  Sources/Vapor/HTTP/Headers/HTTPCookies.swift
  Sources/Vapor/Response/Response+Body.swift
  Sources/Vapor/Utilities/Base32.swift
  Sources/Vapor/Utilities/Base64.swift
  Sources/Vapor/Utilities/BaseN.swift
  Sources/XCTVapor/Exports.swift
  Tests/VaporTests/ConditionalResponseCompressionTests.swift
Labels: semver-minor

#3241 Test MUSL and iOS compilation
  .github/workflows/test.yml
  Package.swift
Labels: no-release-needed

#3246 Fix flaky test
  Tests/VaporTests/PipelineTests.swift
Labels: no-release-needed

#3243 Omit ACAO header instead of empty value
  Sources/Vapor/Middleware/CORSMiddleware.swift
  Tests/VaporTests/AsyncMiddlewareTests.swift
  Tests/VaporTests/MiddlewareTests.swift
Labels: semver-patch
