Repository vapor/vapor, pull requests merged in 2024-05, with the labels that each got.

#3186 Make # of connections accepted per event loop cycle configurable, and raise the default
  Sources/Vapor/HTTP/Server/HTTPServer.swift
Labels: enhancement, semver-minor

#3187 Log source file and line info for errors in ErrorMiddleware when possible
  Sources/Vapor/Error/AbortError.swift
  Sources/Vapor/Middleware/ErrorMiddleware.swift
  Tests/VaporTests/ContentTests.swift
Labels: enhancement, semver-patch

#3168 Mark all functions that use `wait` as `noasync`
  Sources/Development/entrypoint.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Commands/BootCommand.swift
  Sources/Vapor/Commands/RoutesCommand.swift
  Sources/Vapor/Core/Core.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Sources/Vapor/Utilities/DotEnv.swift
  Sources/Vapor/Utilities/FileIO.swift
  Tests/VaporTests/AsyncAuthTests.swift
  Tests/VaporTests/AsyncCacheTests.swift
  Tests/VaporTests/AsyncClientTests.swift
  Tests/VaporTests/AsyncCommandsTests.swift
  Tests/VaporTests/AsyncFileTests.swift
  Tests/VaporTests/AsyncMiddlewareTests.swift
  Tests/VaporTests/AsyncPasswordTests.swift
  Tests/VaporTests/AsyncRequestTests.swift
  Tests/VaporTests/AsyncRouteTests.swift
  Tests/VaporTests/AsyncSessionTests.swift
  Tests/VaporTests/AsyncWebSocketTests.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/FileTests.swift
  Tests/VaporTests/MiddlewareTests.swift
  Tests/VaporTests/PipelineTests.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/SessionTests.swift
Labels: semver-minor

#3189 Add async alternative for Application.shutdown
  Sources/Development/entrypoint.swift
  Sources/Vapor/Application.swift
  Tests/VaporTests/AsyncClientTests.swift
  Tests/VaporTests/AsyncPasswordTests.swift
  Tests/VaporTests/AsyncRequestTests.swift
  Tests/VaporTests/AsyncSessionTests.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/PipelineTests.swift
  Tests/VaporTests/SessionTests.swift
Labels: semver-minor

#3191 Fix availability message
  Sources/Vapor/Application.swift
Labels: semver-patch

#3188 Support compiling against Musl
  Sources/Vapor/Utilities/DirectoryConfiguration.swift
  Sources/Vapor/Utilities/DotEnv.swift
Labels: semver-patch

#3190 Async Serve Command
  Sources/Vapor/Application.swift
  Sources/Vapor/Commands/ServeCommand.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Sources/Vapor/Server/Server.swift
  Sources/XCTVapor/XCTApplication.swift
  Tests/VaporTests/AsyncAuthTests.swift
  Tests/VaporTests/AsyncCacheTests.swift
  Tests/VaporTests/AsyncClientTests.swift
  Tests/VaporTests/AsyncCommandsTests.swift
  Tests/VaporTests/AsyncFileTests.swift
  Tests/VaporTests/AsyncMiddlewareTests.swift
  Tests/VaporTests/AsyncPasswordTests.swift
  Tests/VaporTests/AsyncRouteTests.swift
  Tests/VaporTests/AsyncSessionTests.swift
  Tests/VaporTests/AsyncWebSocketTests.swift
  Tests/VaporTests/FileTests.swift
  Tests/VaporTests/MiddlewareTests.swift
  Tests/VaporTests/PipelineTests.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/SessionTests.swift
Labels: semver-patch

#3193 Add Async Lifecycle Handlers
  Sources/Vapor/Application.swift
  Sources/Vapor/Core/Core.swift
  Sources/Vapor/Utilities/LifecycleHandler.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/AsyncClientTests.swift
  Tests/VaporTests/AsyncRequestTests.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/ServiceTests.swift
Labels: semver-minor

#3192 Update URLEncodedFormEncoder encoding rules
  Sources/Vapor/URLEncodedForm/URLEncodedFormSerializer.swift
  Tests/VaporTests/ContentTests.swift
  Tests/VaporTests/URLEncodedFormTests.swift
Labels: semver-patch

#3195 asyncBoot will no longer try booting server again if it is already booted
  Sources/Vapor/Application.swift
  Tests/VaporTests/ApplicationTests.swift
Labels: semver-patch

#3196 Add Async Storage shutdown
  Sources/Development/routes.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Client/ClientResponse.swift
  Sources/Vapor/Commands/ServeCommand.swift
  Sources/Vapor/HTTP/Client/Application+HTTP+Client.swift
  Sources/Vapor/Server/Application+Servers.swift
  Sources/Vapor/Utilities/Storage.swift
Labels: semver-minor
