Repository vapor/vapor, pull requests merged in 2025-02, with the labels that each got.

#3295 Add VaporTesting to api-docs.yml
  .github/workflows/api-docs.yml
Labels: no-release-needed

#3298 Use singleton NIOThreadPool by default
  Sources/Vapor/Core/Core.swift
Labels: semver-patch

#3282 Android support
  Sources/Vapor/Utilities/DirectoryConfiguration.swift
  Sources/Vapor/Utilities/DotEnv.swift
  Sources/Vapor/Utilities/RFC1123.swift
  Sources/Vapor/Utilities/String+IsIPAddress.swift
  Sources/VaporTesting/+TestingHTTPResponse.swift
  Sources/VaporTesting/TestingApplicationTester.swift
  Sources/VaporTesting/VaporTestingContext.swift
  Sources/XCTVapor/XCTVaporContext.swift
  Tests/VaporTests/AsyncCacheTests.swift
  Tests/VaporTests/AuthenticationTests.swift
  Tests/VaporTests/CacheTests.swift
  Tests/VaporTests/EndpointCacheTests.swift
  Tests/VaporTests/VaporTesting.swift
Labels: semver-patch

#3285 Fix warnings from NIO 2.79.0
  Package.swift
  Sources/Development/routes.swift
  Sources/Vapor/Application.swift
  Sources/Vapor/Environment/Environment+Secret.swift
  Sources/Vapor/HTTP/Server/HTTPServer.swift
  Sources/Vapor/HTTP/Server/HTTPServerUpgradeHandler.swift
  Sources/Vapor/Utilities/DotEnv.swift
  Sources/Vapor/Utilities/FileIO.swift
  Sources/Vapor/View/PlaintextRenderer.swift
  Tests/VaporTests/ApplicationTests.swift
  Tests/VaporTests/AsyncAuthTests.swift
  Tests/VaporTests/AsyncClientTests.swift
  Tests/VaporTests/AsyncEnvironmentTests.swift
  Tests/VaporTests/AsyncRequestTests.swift
  Tests/VaporTests/AsyncRouteTests.swift
  Tests/VaporTests/AuthenticationTests.swift
  Tests/VaporTests/CacheTests.swift
  Tests/VaporTests/ClientTests.swift
  Tests/VaporTests/ContentTests.swift
  Tests/VaporTests/DotEnvTests.swift
  Tests/VaporTests/EndpointCacheTests.swift
  Tests/VaporTests/EnvironmentSecretTests.swift
  Tests/VaporTests/ErrorTests.swift
  Tests/VaporTests/FileTests.swift
  Tests/VaporTests/LoggingTests.swift
  Tests/VaporTests/MetricsTests.swift
  Tests/VaporTests/MiddlewareTests.swift
  Tests/VaporTests/PasswordTests.swift
  Tests/VaporTests/PipelineTests.swift
  Tests/VaporTests/QueryTests.swift
  Tests/VaporTests/RequestTests.swift
  Tests/VaporTests/RouteTests.swift
  Tests/VaporTests/ServerTests.swift
  Tests/VaporTests/ServiceTests.swift
  Tests/VaporTests/ValidationTests.swift
  Tests/VaporTests/ViewTests.swift
  Tests/VaporTests/WebSocketTests.swift
Labels: semver-minor

#3302 Prevent stack overflow by using `NIOLock` instead of `NIOLockedValueBox` during service initialization
  Sources/Vapor/Services/Service.swift
  Tests/VaporTests/ServiceTests.swift
Labels: semver-patch

#3303 Fix warning in service fix
  Sources/Vapor/Services/Service.swift
Labels: semver-patch

#3305 Fix typo in Storage.swift
  Sources/Vapor/Utilities/Storage.swift
Labels: no-release-needed
